# Hyprland Master Configuration
# Sourcing modular components from conf/

source = ~/.config/hypr/conf/colors.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/options.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/startup.conf
