source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/themes/catppuccin-mocha/theme.conf


exec-once = waybar
exec-once = hyprpaper
exec-once = swayosd-server
exec-once = mako
# exec-once = /usr/local/bin/swaync
exec-once = waypaper --restore
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = wl-paste --type text --watch cliphist store # clipboard store text data
exec-once = wl-paste --type image --watch cliphist store # clipboard store image data
exec-once = systemctl --user start hyprpolkitagent
exec-once = kdeconnect-indicator 
exec-once = kitty -e glow /home/abhishek/day_plan.md
# exec-once = wl-clip-persist --clipboard regular

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow



dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    # force_default_wallpaper = -1
 disable_hyprland_logo = true
}


input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0
    touchpad {
        natural_scroll = true 
    }
}
gesture = 3, horizontal, workspace

# gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
# }
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

cursor {
  no_hardware_cursors = true
}
