# Walker Configuration

app_launch_prefix = ""
terminal = "kitty"
placeholder = "Search applications & files..."
show_sub_when_single = true
selection_ui = true

[ui]
width = 500
height = 350
fullscreen = false

[providers]
desktop_applications = true
calculator = true
file_browser = true
command_runner = true
websearch = true
clipboard_history = true
