# Default fallback color variables
$active_border = rgba(c4a7e7ff) rgba(eb6f92ff) 45deg
$inactive_border = rgba(26233aff)
$bg_color = rgb(191724)

general {
    gaps_in = 6
    gaps_out = 12
    border_size = 1
    col.active_border = $active_border
    col.inactive_border = $inactive_border
    layout = dwindle
    allow_tearing = false
    resize_on_border = true
    extend_border_grab_area = 15
    hover_icon_on_border = true
}

decoration {
    rounding = 8

    blur {
        enabled = true
        size = 5
        passes = 2
        new_optimizations = true
        xray = false
        popups = true
    }

    drop_shadow = false
}

cursor {
    no_hardware_cursors = true
    sync_gsettings_theme = true
}

input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = true
        tap-to-click = true
    }

    sensitivity = 0
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = true
    window_direction_monitor_fallback = true
}

xwayland {
    use_nearest_neighbor = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    background_color = $bg_color
}

ecosystem {
    no_donation_nag = true
}
